"""M8 候选 A 的离线规则与策略产物契约。"""

from .chance import CandidateAChance, iter_ordered_deals, ordered_deal_count
from .game import (
    ALLOWED_PLAYER_COUNTS,
    ANTE,
    BET,
    GAME_ID,
    GAME_VERSION,
    ROOT_HISTORY,
    Action,
    CandidateARuleError,
    Deal,
    GameConfig,
    InfoSetSpec,
    PublicState,
    StructureCounts,
    TerminalOutcome,
    acting_player,
    apply_action,
    canonical_history,
    decision_histories,
    derive_public_state,
    information_set_key,
    infosets,
    legal_actions,
    structure_counts,
    terminal_outcome,
)
from .policy import StrategyArtifact, StrategyArtifactError, load_strategy, lookup
from .resources import ResourceEstimate, estimate_resources

__all__ = [
    "ALLOWED_PLAYER_COUNTS",
    "ANTE",
    "BET",
    "GAME_ID",
    "GAME_VERSION",
    "ROOT_HISTORY",
    "Action",
    "CandidateAChance",
    "CandidateARuleError",
    "Deal",
    "GameConfig",
    "InfoSetSpec",
    "PublicState",
    "ResourceEstimate",
    "StrategyArtifact",
    "StrategyArtifactError",
    "StructureCounts",
    "TerminalOutcome",
    "acting_player",
    "apply_action",
    "canonical_history",
    "decision_histories",
    "derive_public_state",
    "estimate_resources",
    "information_set_key",
    "infosets",
    "iter_ordered_deals",
    "legal_actions",
    "load_strategy",
    "lookup",
    "ordered_deal_count",
    "structure_counts",
    "terminal_outcome",
]
