"""Bot 策略层，插件式接口，与具体牌型解耦。"""

from .abstraction import (
    ABSTRACTION_GAME_VERSION,
    ABSTRACTION_PROJECTION_FIELDS,
    ABSTRACTION_TRAINED_PLAYER_COUNTS,
    COVERAGE_IN_ABSTRACTION,
    COVERAGE_INCOMPLETE_INFOSET,
    COVERAGE_OUT_OF_ABSTRACTION,
    COVERAGE_VERSION_MISMATCH,
    DEFAULT_FALLBACK_IDENTIFIER,
    AbstractionContractError,
    AbstractProjection,
    CoverageVerdict,
    FallbackDeclaration,
    FallbackSourceError,
    IncompleteInfosetError,
    OutOfAbstractionError,
    VersionMismatchError,
    build_abstract_projection,
    build_abstraction_key,
    declared_fallback,
    judge_coverage,
    judge_game_state_coverage,
    require_in_abstraction,
)
from .heuristic import HeuristicStrategy
from .interface import Strategy, hero
from .projection import project_for_actor
from .random_strategy import RandomStrategy
from .registry import StrategySpec, UnknownStrategyError, create_strategy, resolve_identifier

__all__ = [
    "Strategy",
    "hero",
    "RandomStrategy",
    "HeuristicStrategy",
    "StrategySpec",
    "UnknownStrategyError",
    "create_strategy",
    "resolve_identifier",
    "project_for_actor",
    "ABSTRACTION_GAME_VERSION",
    "ABSTRACTION_PROJECTION_FIELDS",
    "ABSTRACTION_TRAINED_PLAYER_COUNTS",
    "COVERAGE_IN_ABSTRACTION",
    "COVERAGE_INCOMPLETE_INFOSET",
    "COVERAGE_OUT_OF_ABSTRACTION",
    "COVERAGE_VERSION_MISMATCH",
    "DEFAULT_FALLBACK_IDENTIFIER",
    "AbstractProjection",
    "AbstractionContractError",
    "CoverageVerdict",
    "FallbackDeclaration",
    "FallbackSourceError",
    "IncompleteInfosetError",
    "OutOfAbstractionError",
    "VersionMismatchError",
    "build_abstract_projection",
    "build_abstraction_key",
    "declared_fallback",
    "judge_coverage",
    "judge_game_state_coverage",
    "require_in_abstraction",
]
