"""Bot 策略层，插件式接口，与具体牌型解耦。"""

from .abstraction import (
    ABSTRACTION_GAME_VERSION,
    ABSTRACTION_PROJECTION_FIELDS,
    ABSTRACTION_TRAINED_PLAYER_COUNTS,
    COVERAGE_IN_ABSTRACTION,
    COVERAGE_INCOMPLETE_INFOSET,
    COVERAGE_OUT_OF_ABSTRACTION,
    COVERAGE_VERSION_MISMATCH,
    DEFAULT_FALLBACK_IDENTIFIER,
    AbstractionContractError,
    AbstractProjection,
    CoverageVerdict,
    FallbackDeclaration,
    FallbackSourceError,
    IncompleteInfosetError,
    OutOfAbstractionError,
    VersionMismatchError,
    build_abstract_projection,
    build_abstraction_key,
    declared_fallback,
    judge_coverage,
    judge_game_state_coverage,
    require_in_abstraction,
)
from .artifact import (
    ARTIFACT_TYPE,
    LookupOutcome,
    LookupRegistry,
    LookupStatus,
    LookupTable,
    StrategyArtifact,
    StrategyArtifactError,
    StrategyInfoset,
    load_lookup_registry,
    load_lookup_table,
    load_strategy_artifact,
)
from .heuristic import HeuristicStrategy
from .interface import Strategy, hero
from .lookup_budget import (
    DECISION_BUDGET_MS,
    LookupBudgetReport,
    PlayerCountCoverage,
    build_report,
    summarize_decision_latencies,
)
from .position_projection import (
    POSITION_ACTION_TOKENS,
    POSITION_BASIS,
    POSITION_PROJECTION_FIELDS,
    POSITION_PROJECTION_VERSION,
    POSITION_STREETS,
    PositionContractError,
    PositionEncodingError,
    PositionProjection,
    PositionProjectionError,
    PublicAction,
    StreetActionLine,
    blind_relative_seats,
    build_position_projection,
    build_public_actions,
    project_position_for_actor,
    relative_seat,
    street_action_order,
)
from .projection import project_for_actor
from .random_strategy import RandomStrategy
from .registry import StrategySpec, UnknownStrategyError, create_strategy, resolve_identifier

__all__ = [
    "Strategy",
    "hero",
    "RandomStrategy",
    "HeuristicStrategy",
    "StrategySpec",
    "UnknownStrategyError",
    "create_strategy",
    "resolve_identifier",
    "project_for_actor",
    "ABSTRACTION_GAME_VERSION",
    "ABSTRACTION_PROJECTION_FIELDS",
    "ABSTRACTION_TRAINED_PLAYER_COUNTS",
    "COVERAGE_IN_ABSTRACTION",
    "COVERAGE_INCOMPLETE_INFOSET",
    "COVERAGE_OUT_OF_ABSTRACTION",
    "COVERAGE_VERSION_MISMATCH",
    "DEFAULT_FALLBACK_IDENTIFIER",
    "AbstractProjection",
    "AbstractionContractError",
    "CoverageVerdict",
    "FallbackDeclaration",
    "FallbackSourceError",
    "IncompleteInfosetError",
    "OutOfAbstractionError",
    "VersionMismatchError",
    "build_abstract_projection",
    "build_abstraction_key",
    "declared_fallback",
    "judge_coverage",
    "judge_game_state_coverage",
    "require_in_abstraction",
    "POSITION_PROJECTION_VERSION",
    "POSITION_BASIS",
    "POSITION_STREETS",
    "POSITION_ACTION_TOKENS",
    "POSITION_PROJECTION_FIELDS",
    "PositionProjectionError",
    "PositionContractError",
    "PositionEncodingError",
    "PublicAction",
    "StreetActionLine",
    "PositionProjection",
    "relative_seat",
    "blind_relative_seats",
    "street_action_order",
    "build_public_actions",
    "build_position_projection",
    "project_position_for_actor",
    "ARTIFACT_TYPE",
    "LookupOutcome",
    "LookupRegistry",
    "LookupStatus",
    "LookupTable",
    "StrategyArtifact",
    "StrategyArtifactError",
    "StrategyInfoset",
    "load_lookup_registry",
    "load_lookup_table",
    "load_strategy_artifact",
    "DECISION_BUDGET_MS",
    "LookupBudgetReport",
    "PlayerCountCoverage",
    "build_report",
    "summarize_decision_latencies",
]
